#include "Graaf.h"
#include <boost/python.hpp>

using namespace boost::python;

BOOST_PYTHON_MODULE(pest_sci_calculator)
{
    class_<Graaf, boost::noncopyable>("Graaf")
        .def("add_node", &Graaf::add_node)
        .def("add_node_like_first", &Graaf::add_node_like_first)
        .def("add_node_like_last", &Graaf::add_node_like_last)
        .def("create_node", &Graaf::create_node)
        .def("get_position", &Graaf::get_position)
        .def("change_how_to_total", &Graaf::change_how_to_total)
        .def("change_all_group_names", &Graaf::change_all_group_names)
        .def("change_name", &Graaf::change_name)
        .def("get_position_group", &Graaf::get_position_group)
        .def("change_name_group", &Graaf::change_name_group)
        .def("return_all_group_names", &Graaf::return_all_group_names)
        .def(" return_all_node_names", &Graaf::return_all_node_names)
        .def("change_group", &Graaf::change_group)
        .def("change_name_by_name", &Graaf::change_name_by_name)
        .def("delete_node", &Graaf::delete_node)
        .def("delete_all_nodes", &Graaf::delete_all_nodes)
        .def("add_step_by_values", &Graaf::add_step_by_values)
        .def("change_step_constant", &Graaf::change_step_constant)
        .def("change_times_step", &Graaf::change_times_step)
        .def("change_divide_step", &Graaf::change_divide_step)
        .def("change_both_ways_step", &Graaf::change_both_ways_step)
        .def("change_from_step", &Graaf::change_from_step)
        .def("change_to_step", &Graaf::change_to_step)
        .def("change_first_step_node", &Graaf::change_first_step_node)
        .def("change_second_step_node", &Graaf::change_second_step_node)
        .def("get_position_step", &Graaf::get_position_step)
        .def("delete_step", &Graaf::delete_step)
        .def("delete_step_by_groups", &Graaf::delete_step_by_groups)
        .def("delete_all_steps", &Graaf::delete_all_steps)
        .def("get_groups", &Graaf::get_groups)
        .def("update_all_total", &Graaf::update_all_total)
        .def("all_steps_between_nodes", &Graaf::all_steps_between_nodes)
        .def("all_update_dt", &Graaf::all_update_dt)
        .def("all_add_dt_to_groups", &Graaf::all_add_dt_to_groups)
        .def("time_step", &Graaf::time_step)
        .def("node_change_step_constant", &Graaf::node_change_step_constant)
        .def("node_change_times_step", &Graaf::node_change_times_step)
        .def("node_change_divide_ste", &Graaf::node_change_divide_step)
        .def("node_change_from_step", &Graaf::node_change_from_step)
        .def("node_change_both_ways_step", &Graaf::node_change_both_ways_step)
        .def("node_change_to_step", &Graaf::node_change_to_step)
        .def("allnodes_change_step_constant", &Graaf::allnodes_change_step_constant)
        .def("allnodes_change_times_step", &Graaf::allnodes_change_times_step)
        .def("allnodes_change_divide_ste", &Graaf::allnodes_change_divide_step)
        .def("allnodes_change_from_step", &Graaf::allnodes_change_from_step)
        .def("allnodes_change_both_ways_step", &Graaf::allnodes_change_both_ways_step)
        .def("allnodes_change_to_step", &Graaf::allnodes_change_to_step)
        .def("output_node_file_add_header", &Graaf::output_node_file_add_header)
        .def("output_node_file_add_current_groups", &Graaf::output_node_file_add_current_groups)
        .def("run_and_output_to_txt_per_node", &Graaf::run_and_output_to_txt_per_node)
        .def("change_all_group_names_python", &Graaf::change_all_group_names_python)
        .def("return_all_groups_names_python", &Graaf::return_all_groups_names_python)
        .def("return_all_node_names_python", &Graaf::return_all_node_names_python)
        .def("get_groups_python", &Graaf::get_groups_python)
        .def("node_change_dividetimes", &Graaf::node_change_dividetimes)
        .def("allnodes_change_timesdivide_step", &Graaf::allnodes_change_timesdivide_step)
        .def("add_step_by_values_python", &Graaf::add_step_by_values_python)
        .def("add_step_to_node_python", &Graaf::add_step_to_node_python)
        .def("change_how_to_total_python", &Graaf::change_how_to_total_python)
        .def("get_n_node", &Graaf::get_n_node)
        .def("check_if_zero", &Graaf::check_if_zero)
        .def("get_group_all_nodes", &Graaf::get_group_all_nodes)
        .def("get_groups_all_nodes_python", &Graaf::get_groups_all_nodes_python)
        .def("get_group_name", &Graaf::get_group_name)
        .def("n_steps", &Graaf::n_steps)
        .def("node_steps", &Graaf::node_steps)
        .def("get_groups_custom_python", &Graaf::get_groups_custom_python)
        .def("get_group_all_nodes_custom_python", &Graaf::get_group_all_nodes_custom_python)
        .def("get_dt_sign", &Graaf::get_dt_sign)
        .def("get_group_dt_all_nodes_custom_python", &Graaf::get_group_dt_all_nodes_custom_python)
        .def("get_group_dt_all_nodes_python", &Graaf::get_group_dt_all_nodes_python)

        ;
}
